#pragma once

#define UASSET_JSON_EXPORTER_VERSION_MAJOR 1
#define UASSET_JSON_EXPORTER_VERSION_MINOR 7
#define UASSET_JSON_EXPORTER_VERSION_PATCH 1
#define UASSET_JSON_EXPORTER_VERSION_STRING TEXT("1.7.1")
